FROM node:lts
WORKDIR /usr/src/app/
COPY package*.json ./
RUN npm install
#RUN npm install abcjs
#RUN npx astro add react
#COPY . .
#CMD ["npm", "run", "dev","--", "--port ", "3000", "--host"]
CMD ["npm", "run", "dev"]