version: '3.8'
services:
  jupyter-lab:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./:/tf-env
    entrypoint: 
      jupyter lab --ip='0.0.0.0' --allow-root --no-browser
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

